version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      DEV_DATABASE_HOST: ${DEV_DATABASE_HOST}
      DEV_DATABASE_USERNAME: ${DEV_DATABASE_USERNAME}
      DEV_DATABASE_PASSWORD: ${DEV_DATABASE_PASSWORD}
      DEV_DATABASE_PORT: ${DEV_DATABASE_PORT}
      DEV_DATABASE_NAME: ${DEV_DATABASE_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
      FRONT_URL: ${FRONT_URL}
      EMAIL_USER: ${EMAIL_USER}
      BREVO_API_KEY: ${BREVO_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - frontend-dist:/app/dist
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DEV_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE_NAME}
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend-dist:/usr/share/nginx/html
      - /bin/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend

volumes:
  database:
  frontend-dist:
